
version: "3.7"

services:
  app:
    build:
      context: .
      target: base
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py wait_for_db && python manage.py runserver 0.0.0
      .0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASSWORD=123456
    depends_on:
      - db


  db:
    image: postgres:10-alpine
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

volumes:
  db:
    driver: local